FROM python:3.12-slim

COPY requirements_graphs.txt requirements_graphs.txt
RUN pip install -r requirements_graphs.txt

WORKDIR /app
COPY make_graphs.py make_graphs.py

CMD ["python", "make_graphs.py"]
